# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Builder-Auth
version:      0.06
version_from: lib/CGI/Builder/Auth.pm
installdirs:  site
requires:
    Carp:                          0
    CGI::Builder:                  1.11
    Class::constr:                 1.75
    Class::props:                  1.7
    Digest::MD5 :                  0
    File::Basename:                0
    Scalar::Util:                  0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
